sudo: required
# language: go
go:
  - "1.10.x"
  
arch: ppc64le

services:
  - docker

script:
  - bash ./promremotebench_ubi8.2.sh
  - go vet
  
  

#addons:
#  apt:
#    packages:
#      # Install the latest version of Docker.
#      - docker-ce

#services:
#  - docker

  
